name: test_app
description: "Assignment App /Datamites."
 
publish_to: 'none'
 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  connectivity_plus: ^6.1.3
  http: ^1.3.0
  cached_network_image: ^3.4.1
  workmanager: ^0.5.2
  drift: 2.23.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.23.0
  build_runner: ^2.4.13

flutter:
   
  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
